### ISSUE TITLE
change copywritr from © finalforeach to © finalforeach and contributors

### ISSUE THREAD

**Issue by realeatham** [FinalForEach/Cosmic-Reach-Localization#2]

**Comment by FinalForEach** [comment]
This is part of the reason nothing has been put here yet, a proper credits need to be put in the game before I can accept contributions

**Comment by FinalForEach** [comment]
Also why this is a separate library, so that copyright is shared only with the files in this repo, and not the entire software

**Comment by realeatham** [comment]
> This is part of the reason nothing has been put here yet, a proper credits need to be put in the game before I can accept contributions

Ok





> Also it's why this is a separate library, so that copyright is shared only with the files in this repo, and not the entire software

That doesn't make much sense, as people only copywrite the specific modifications they make to this. It should still be in a separate repo tho because otherwise the whole software would be MIT

**Comment by FinalForEach** [comment]
> That doesn't make much sense, as people only copywrite the specific modifications they make to this. It should still be in a separate repo tho because otherwise the whole software would be MIT

That's exactly what I'm getting at.

**Comment by realeatham** [comment]
> That's exactly what I'm getting at.

Ok

**Comment by FinalForEach** [comment]
Updated the MIT license.
