### ISSUE TITLE
make the format the same or similar to https://github.com/CRModders/Flux-Translations

### ISSUE THREAD

**Issue by realeatham** [FinalForEach/Cosmic-Reach-Localization#3]
[CRModders/Flux-Translations](https://github.com/CRModders/Flux-Translations)

There is also another mod which adds translation https://discord.com/channels/1198501071363002408/1220213503227334707

**Comment by Nanobass** [comment]
@FinalForEach If you have questions about the file format used by Flux API, then ask me. I made the format

**Comment by FinalForEach** [comment]
Closing following the language format refactor.
