### ISSUE TITLE
Some text strings go out of bounds on the buttons; No way to translate worldType types

### ISSUE THREAD

**Issue by DAHASAG** [FinalForEach/Cosmic-Reach-Localization#38]
As stated in the title. Some translated strings (i checked uk_ua and ru_ru) go out of the bounds of buttons in game (https://tinyurl.com/52t5p5w8 for example). Will there be any fix for this? Like line wrapping, or text scrolling?
Additionally, i couldn't find anywhere the lines for worldType options (Moon, Flat world and Nostalgic Islands), so i believe they are untranslatable for now.

**Comment by FinalForEach** [comment]
A very temporary fix was put in for the bounds issue in 0.1.23, I need to consider a bit more about the format before giving the translation keys for the world types
