### ISSUE TITLE
How (Or should) the title be translated?

### ISSUE THREAD

**Issue by JerryDELUXE** [FinalForEach/Cosmic-Reach-Localization#82]
Should it be kept in English, be translated, be transliterated or something else?

**Comment by Neuxs0** [comment]
Titles/names on apps, names, games, etc. aren't something that you translate when doing translations, for example:
> I downloaded the new game Apex Legends on my phone.
would become
> 新しいゲームApex Legendsを携帯電話にダウンロードしました
in japanese, the game name "Apex Legends" doesn't change.

**Comment by FinalForEach** [comment]
Kept in English, otherwise I suspect branding issues may occur.

**Comment by ImpSteve** [comment]
Leave title as it is, in English. But since such a question arose, a glossary should be created in the future with strings that should not be translated normally
